### PR TITLE
Update dependencies to support React v18

### LINKED ISSUE #12: Update React dependency to version 18

### PR DESCRIPTION
**Pull request by andrewrubin**
# What was changed?
- Update **dev** dependencies to react 18
- Update peer dependencies to react 17 – 18
- Update .nvmrc file to use Node 18 (per other wethegit packages)
- VS Code workspace settings cleanup

Closes #12

### CODE REVIEW

**Review by marlonmarcello — DISMISSED** [review]
Just gotta update the types too:

```
"@types/react": "^18.2.48",
"@types/react-dom": "^18.2.18",
```

Otherwise :shipit:

**Comment by marlonmarcello** [comment]
Ahh, please also update the node version in CI [here](https://github.com/wethegit/react-marquee/blob/main/.github/workflows/publish-package.yml)

**Comment by andrewrubin** [comment]
Good catch @marlonmarcello , those are done now

**Review by marlonmarcello — APPROVED** [review]

**Comment by marlonmarcello** [comment]
@andrewrubin forgot another thing, you need to update the Playground where we render the component
https://github.com/wethegit/react-marquee/blob/main/src/main.jsx#L48

**Comment by marlonmarcello** [comment]
One thing to consider is the version. This will still work on React 17 as noted by the `peerDependencies` so there is no need to bump a full version if you don't want to.

**Comment by andrewrubin** [comment]
Thanks for the notes! Those are done. I've bumped the patch version instead

**Review by marlonmarcello — APPROVED** [review]

**Pull request merged**
