### PR TITLE
fix: set default duration > 0

### PR DESCRIPTION
**Pull request by chanroyc**
### Description of the Issue

Marquee is not playing on FireFox unless window is resized or reduced motion is toggled.

### Fix

Default duration state has been set to 1 (> 0).
When the default duration is > 0, Marquee will play as intended on Firefox

### Question
Anyone have any idea why this is happening?

### CODE REVIEW

**Comment by NicholasLancey** [comment]
This was a super weird one. Like @chanroyc said, if the duration is set to 0 by default, the Marquee won't play until the browser is resized. This **only** happens on Firefox. Having a default value greater than 0 fixes this. 🤷 

I don't totally understand **why** that works - but either way I've tested locally and it looks good to me!

**Review by NicholasLancey — DISMISSED** [review]

**Comment by rvno** [comment]
I had a similar issue with the Marquee a while back where I ended up using the code from Splatoon that @ste-vg wrote, though my issue was in Safari.. I think also adding in a `.01s` animation-delay helped but I'll see if I can poke around a bit more, otherwise this looks fine to me, too 🤷‍♂️

**Comment by andrewrubin** [comment]
I have a sneaking suspicion that this is related to how we're measuring the content. In the past I've seen Firefox shit the bed when trying to run something like `getBoundingClientRect()` before the page is fully loaded. This could be similar, albeit for `clientWidth`. That would explain why it works on resize.

Since we don't want to add any image loaded checkers or anything (after all, it's possible people will not use this component for images), maybe we should try to only render this component once the content has loaded, and see if that fixes it?

**Comment by chanroyc** [comment]
Thanks guys. So instead of setting duration to 1, I created a new state called `isPlaying` which defaults to false.

The state will be set to the `playing` prop after all the calcs.

When `isPlaying` is true, `.is-playing` classname will be added. I have moved the animation into `.is-playing`

Let me know what you guys think.

**Comment by marlonmarcello** [comment]
I think this approach will make the content "jump" if you go from true to false and vice - versa for the playing prop as we are now completely removing the animation

**Pull request closed without merging**
